In [1]:
import numpy as np
import pandas as pd

In [2]:
df=pd.read_csv("movie.csv")

In [3]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 27278 entries, 0 to 27277
Data columns (total 3 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   movieId  27278 non-null  int64
 1   title    27278 non-null  object
 2   genres   27278 non-null  object
dtypes: int64(1), object(2)
memory usage: 639.5+ KB

In [4]:
df.nunique()

movieId    27278
title      27262
genres      1342
dtype: int64

In [5]:
df1=df.duplicated()
df1

0        False
1        False
2        False
3        False
4        False
         ...
27273    False
27274    False
27275    False
27276    False
27277    False
Length: 27278, dtype: bool

In [6]:
df2=df.fillna
df2

<bound method NDFrame.fillna of        movieId                               title  \
0            1                    Toy Story (1995)
1            2                      Jumanji (1995)
2            3             Grumpier Old Men (1995)
3            4            Waiting to Exhale (1995)
4            5  Father of the Bride Part II (1995)
...        ...                                 ...
27273   131254        Kein Bund für's Leben (2007)
27274   131256       Feuer, Eis & Dosenbier (2002)
27275   131258                  The Pirates (2014)
27276   131260                 Rentun Ruusu (2001)
27277   131262                    Innocence (2014)

                                            genres
0      Adventure|Animation|Children|Comedy|Fantasy
1                       Adventure|Children|Fantasy
2                                   Comedy|Romance
3                             Comedy|Drama|Romance
4                                           Comedy
...                                            ...
27273                                       Comedy
27274                                       Comedy
27275                                    Adventure
27276                           (no genres listed)
27277                     Adventure|Fantasy|Horror

[27278 rows x 3 columns]>

In [7]:
df.isnull().sum()

movieId    0
title      0
genres     0
dtype: int64

In [8]:
df.duplicated().sum()

np.int64(0)

In [9]:
df.describe()

             movieId
count   27278.000000
mean    59855.480570
std     44429.314697
min         1.000000
25%      6931.250000
50%     68068.000000
75%    100293.250000
max    131262.000000

In [10]:
df.head()

,movieId,title,genres
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy
1,2,Jumanji (1995),Adventure|Children|Fantasy
2,3,Grumpier Old Men (1995),Comedy|Romance
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance
4,5,Father of the Bride Part II (1995),Comedy

In [11]:
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression

In [12]:
x=df[['movieId']]
y=df['genres']

In [13]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=50)

In [14]:
x_train

       movieId
8571     26046
6045      6144
5505      5604
14606    73056
24582   116305
...        ...
15649    79627
22637   108473
10123    33539
5600      5699
14000    70204

[19094 rows x 1 columns]

In [15]:
y_test

2234                      Comedy|Drama
11734          Horror|Mystery|Thriller
7176                             Drama
22093                   Drama|Thriller
12994                            Drama
                     ...
13681                      Documentary
11758            Action|Drama|Thriller
16512                           Comedy
17911                    Drama|Romance
24016    Comedy|Drama|Romance|Thriller
Name: genres, Length: 8184, dtype: object

In [16]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [17]:
tfidf=TfidfVectorizer()

In [18]:
df['genres_clean']=df['genres'].str.replace('|',' ',regex=False)
df['genres_clean']

0        Adventure Animation Children Comedy Fantasy
1                         Adventure Children Fantasy
2                                     Comedy Romance
3                               Comedy Drama Romance
4                                             Comedy
                            ...
27273                                         Comedy
27274                                         Comedy
27275                                      Adventure
27276                             (no genres listed)
27277                       Adventure Fantasy Horror
Name: genres_clean, Length: 27278, dtype: object

In [19]:
genres_tfidf=tfidf.fit_transform(df['genres'])

In [20]:
genres_tfidf

<Compressed Sparse Row sparse matrix of dtype 'float64'
	with 56971 stored elements and shape (27278, 24)>

In [21]:
genre_df=pd.DataFrame(
    genres_tfidf.toarray(),
    columns=tfidf.get_feature_names_out()
)

In [22]:
df1=pd.concat([df,genre_df],axis=1)

In [23]:
df1

,movieId,title,genres,genres_clean,action,adventure,animation,children,comedy,crime,...,listed,musical,mystery,no,noir,romance,sci,thriller,war,western
0,1,Toy Story (1995),Adventure|Animation|Children|Comedy|Fantasy,Adventure Animation Children Comedy Fantasy,0.0,0.419151,0.518269,0.505742,0.264175,0.0,...,0.00000,0.0,0.0,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0
1,2,Jumanji (1995),Adventure|Children|Fantasy,Adventure Children Fantasy,0.0,0.515311,0.000000,0.621768,0.000000,0.0,...,0.00000,0.0,0.0,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0
2,3,Grumpier Old Men (1995),Comedy|Romance,Comedy Romance,0.0,0.000000,0.000000,0.000000,0.602583,0.0,...,0.00000,0.0,0.0,0.00000,0.0,0.798056,0.0,0.0,0.0,0.0
3,4,Waiting to Exhale (1995),Comedy|Drama|Romance,Comedy Drama Romance,0.0,0.000000,0.000000,0.000000,0.544541,0.0,...,0.00000,0.0,0.0,0.00000,0.0,0.721186,0.0,0.0,0.0,0.0
4,5,Father of the Bride Part II (1995),Comedy,Comedy,0.0,0.000000,0.000000,0.000000,1.000000,0.0,...,0.00000,0.0,0.0,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27273,131254,Kein Bund für's Leben (2007),Comedy,Comedy,0.0,0.000000,0.000000,0.000000,1.000000,0.0,...,0.00000,0.0,0.0,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0
27274,131256,"Feuer, Eis & Dosenbier (2002)",Comedy,Comedy,0.0,0.000000,0.000000,0.000000,1.000000,0.0,...,0.00000,0.0,0.0,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0
27275,131258,The Pirates (2014),Adventure,Adventure,0.0,1.000000,0.000000,0.000000,0.000000,0.0,...,0.00000,0.0,0.0,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0
27276,131260,Rentun Ruusu (2001),(no genres listed),(no genres listed),0.0,0.000000,0.000000,0.000000,0.000000,0.0,...,0.57735,0.0,0.0,0.57735,0.0,0.000000,0.0,0.0,0.0,0.0
27277,131262,Innocence (2014),Adventure|Fantasy|Horror,Adventure Fantasy Horror,0.0,0.555125,0.000000,0.000000,0.000000,0.0,...,0.00000,0.0,0.0,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0

In [24]:
df1=df1.drop(columns='genres')

In [25]:
df1

,movieId,title,genres_clean,action,adventure,animation,children,comedy,crime,documentary,...,listed,musical,mystery,no,noir,romance,sci,thriller,war,western
0,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy,0.0,0.419151,0.518269,0.505742,0.264175,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0
1,2,Jumanji (1995),Adventure Children Fantasy,0.0,0.515311,0.000000,0.621768,0.000000,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0
2,3,Grumpier Old Men (1995),Comedy Romance,0.0,0.000000,0.000000,0.000000,0.602583,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0,0.798056,0.0,0.0,0.0,0.0
3,4,Waiting to Exhale (1995),Comedy Drama Romance,0.0,0.000000,0.000000,0.000000,0.544541,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0,0.721186,0.0,0.0,0.0,0.0
4,5,Father of the Bride Part II (1995),Comedy,0.0,0.000000,0.000000,0.000000,1.000000,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27273,131254,Kein Bund für's Leben (2007),Comedy,0.0,0.000000,0.000000,0.000000,1.000000,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0
27274,131256,"Feuer, Eis & Dosenbier (2002)",Comedy,0.0,0.000000,0.000000,0.000000,1.000000,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0
27275,131258,The Pirates (2014),Adventure,0.0,1.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0
27276,131260,Rentun Ruusu (2001),(no genres listed),0.0,0.000000,0.000000,0.000000,0.000000,0.0,0.0,...,0.57735,0.0,0.0,0.57735,0.0,0.000000,0.0,0.0,0.0,0.0
27277,131262,Innocence (2014),Adventure Fantasy Horror,0.0,0.555125,0.000000,0.000000,0.000000,0.0,0.0,...,0.00000,0.0,0.0,0.00000,0.0,0.000000,0.0,0.0,0.0,0.0

In [26]:
from sklearn.metrics.pairwise import cosine_similarity

In [27]:
similarity_matrix=cosine_similarity(genres_tfidf)

In [28]:
similarity_matrix.shape

(27278, 27278)

In [29]:
indices=pd.Series(df1.index,index=df1['title']).drop_duplicates()

In [30]:
from operator import index
def recommend(title,top_n=5):
  if title not in indices:
    return "Movie Not Found"

  idx=indices[title]

  # Get similarity scores
  sim_scores=list(enumerate(similarity_matrix[idx]))

  # Sort movies based on similarity scores
  sim_scores=sorted(sim_scores,key=lambda x:x[1],reverse=True)

  # Skip itself
  sim_scores=sim_scores[1:top_n+1]

  movie_indices=[i[0] for i in sim_scores]

  return df1[['title','genres_clean']].iloc[movie_indices]

In [31]:
df1.head()

,movieId,title,genres_clean,action,adventure,animation,children,comedy,crime,documentary,...,listed,musical,mystery,no,noir,romance,sci,thriller,war,western
0,1,Toy Story (1995),Adventure Animation Children Comedy Fantasy,0.0,0.419151,0.518269,0.505742,0.264175,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
1,2,Jumanji (1995),Adventure Children Fantasy,0.0,0.515311,0.000000,0.621768,0.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0
2,3,Grumpier Old Men (1995),Comedy Romance,0.0,0.000000,0.000000,0.000000,0.602583,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.798056,0.0,0.0,0.0,0.0
3,4,Waiting to Exhale (1995),Comedy Drama Romance,0.0,0.000000,0.000000,0.000000,0.544541,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.721186,0.0,0.0,0.0,0.0
4,5,Father of the Bride Part II (1995),Comedy,0.0,0.000000,0.000000,0.000000,1.000000,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.000000,0.0,0.0,0.0,0.0

In [32]:
recommend("Toy Story (1995)")

,title,genres_clean
2209,Antz (1998),Adventure Animation Children Comedy Fantasy
3027,Toy Story 2 (1999),Adventure Animation Children Comedy Fantasy
3663,"Adventures of Rocky and Bullwinkle, The (2000)",Adventure Animation Children Comedy Fantasy
3922,"Emperor's New Groove, The (2000)",Adventure Animation Children Comedy Fantasy
4790,"Monsters, Inc. (2001)",Adventure Animation Children Comedy Fantasy